[package]
name = "cipher-three"
version = "0.3.0"
authors = ["avastmick <avastmick@outlook.com>"]

[dependencies]
argparse = "*"
lazy_static = "*"
maplit = "*"
rand = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = "2"
